[WIP] Makefile for windev
openoereb/oereb_client pull request #233
Opened 2021-12-02 11:20 UTC by voisardf

Added an new target to the Makefile for a local windows environment with paster

2021-12-02 11:20 UTC, voisardf commented
I accidentaly added some files I need to remove first

2021-12-02 12:16 UTC, voisardf commented
@kdeininger I removed the unecessary files, PR is ready for review now.
I do not know yet, why the CI fails

2021-12-02 14:37 UTC, kdeininger requested changes

2021-12-02 14:37 UTC, kdeininger commented on Makefile
> +VENV_BIN ?= .venv/Scripts/
The CI fails with the following error:

```
make: .venv/Scripts/pip: Command not found
```

You need to use `VENV_BIN ?= .venv/bin/` here and create a new file, e.g. `windows.mk` with the follwing content:

```
VENV_BIN ?= .venv/Scripts/
include Makefile
```

Then use `make -f windows.mk serve-windev` to start the server.

2021-12-03 08:30 UTC, voisardf commented
@kdeininger : should be fixed now. Working on local dev

2021-12-03 08:57 UTC, kdeininger approved these changes

2021-12-03 08:57 UTC, kdeininger approved these changes

2021-12-03 09:03 UTC, merged